name = "Basic"
license = "MIT"
licenselink = "https://github.com/nikldev0/plantcode/blob/main/themes/basic/LICENSE"
description = "blog theme"
homepage = "/"
min_version = "0.41.0"

[author]
  name = "Nikhil.K"



